language = {"version" : "0.0.1"};
language.toast = {
    "version" : "0.0.1",
    "gamestart": "Game starts..!",
    "regCalled": "Register called",
    "enterKeyword": "Please enter some keywords.",
    "wrongMgs": "something went wrong",
    "contestStarted": "Contest Started",
    "contestFail": "Contest Failed to Start",
    "contestStarting": "Starting Contest",
    "invalidEmail": "Not a valid e-mail address",
    "batchstarted": "batch started",
    "sentpicture": " has sent you a sentiment!!",
    "globalFeeddata": "Global Feed <i class='checkmark icon'></i>",
    "globalFeederror": "Global Feed <i class='warning icon'></i>",
    "globalFeed": "Global Feed <i class='cloud upload icon'></i>",
    "populardata": "Popular sentiments <i class='checkmark icon'></i>",
    "popularerror": "Popular sentiment <i class='warning icon'></i>",
    "popular": "Popular sentiment <i class='cloud upload icon'></i>",
    "notRecognize": "I didn't recognize you. Sorry !!",
    "noDatabase": "Not found in database",
    "loginWithInstagram": "login with instagram first",
    "somethingWrong": "something went wrong !!",
    "followdata": "Follow <i class='checkmark icon'></i>",
    "followerror": "Follow <i class='warning icon'></i>",
    "follow": "Follow <i class='cloud upload icon'></i>",
    "feed": "Feed <i class='cloud upload icon'></i>", 
    "feederror": "Feed <i class='warning icon'></i>",
    "nofeed": "No Feeds as of now.",
    "feedincomplete": "Request for feed incomplete.",
    "feedSucess": "Feed <i class='checkmark icon'></i>",
    "likeerror": "Like <i class='warning icon'></i>",
    "likedata": "Like",
    "like": "Like <i class='cloud upload icon'></i>",
    "reqToCommentCompleted": "Request to comment completed.",
    "reqToCommentFailed": "Request to comment failed.",
    "reqToCommentSent": "Request to comment is sent.",
    "votedtwice": "You voted twice.",
    "youRecommendPic1": "You recommended this sentiment to ",
    "youRecommendPic2": " Will they tap the same spot?",
    "hateNpromote": "Yikes! You diss it and share this sentiment loudly ",
    "loveNpromote": "Damn nice.. You like and share this sentiment loudly ",
    "love": "You like this sentiment. Quitely.",
    "hate": "You dislike the sentiment… But don’t raise the alarm.",
    "Recentslabel": "Recents",
    "languageButton": "Language <i class='globe icon'></i>",
    "shareApp": "<i class='url icon'></i> Share",
    "Logout": "<i class='sign out icon'></i> Log Out",
    "about": "<i class='font icon'></i> About",
    "alreadyMessage": "Don't recognize yourself? <br><br> Log in with instagram. ",
    "Login With Instagram": "Login With Instagram",
    "Contact Us": "<i class='phone icon'></i> Contact Us ",
    "Push Notification": "PushNotification",
    "optimize": "Optimize <input id='optimizeCheckBox' type='checkbox'>",
    "help": "<b>Help</b>",
    "Game": "<b>Game</b>",
    "Tutorial": "<i class='magic icon'></i> Tutorial",
    "Instruction": "<i class='info icon'></i> Instruction ",
    "Walkthrough": "<i class='won icon'> </i>Walkthrough ",
    "ContactUsPopUp": "Please email us any bugs you find: <br/>tapmate@youiest.com<br/>Thank you for braving the bugs! <br/> We hope you agree this is crazily great.",
    "AboutUsPopUp": "Tapmate uses the Instagram(tm) API and is not endorsed or certified by Instagram(tm) logos and trademarks displayed on this app are property of Instagram, Inc.<br> <div id='hideAboutUsPopUp' class='circular ui button'>ok</div>",
    "termsandcondition": "<b><a href='https://www.docracy.com/0e2d355wq30/youiest-tapmate-privacy-policy?highlightComment=-1&startOnComments=false' target='_blank'> Terms and Conditions</a></b><p>By using our website you agree to be legally bound by these <a href='https://www.docracy.com/0e2d355wq30/youiest-tapmate-privacy-policy?highlightComment=-1&startOnComments=false' target='_blank'> Terms and Conditions</a>, which shall take effect immediately on your first use of our website. If you do not agree to be legally bound by all the following terms please do not access and/or use our website.</p><p>We may change these terms at any time by posting changes online. Please review these terms regularly to ensure you are aware of any changes made by us. Your continued use of our website after changes are posted means you agree to be legally bound by these terms as updated and/or amended.</p>",
    "I aggree": "I agree",
    "sendMail": " Send Mail ",
    "loginwithInsta": "<i class='instagram icon'></i> Log in with Instagram",
    "loginwithfb": "<i class='facebook sign icon'> </i> Log in with Facebook",
    "loginwithgoog": "<i class='google plus sign icon'></i> Log in with Google",
    "videotutorial": "<i class='video icon'></i>Video tutorial",
    "accounts": "<b>Accounts</b>",
    "settings": "<b>Settings</b>",
    "tapmate": "<b>Tapmate</b>",
    "menubug": "<b>Development</b>",
    "uvotethispic": "You voted this pic!",
    "uguess": "You guessed ",
    "wouldtap": " would tap here!",
    "urfriends": "Your friends on Instagram.",
    "got": "got it",
    "ptsfromyourvote": "pts from your vote.",
    "ptsfrom": "pts from @",
    "by": "by @",
    "pic": "sentiment.",
    "hassendpicture": "has sent you a sentiment.",
    "atheader": "Alert",
    "atmessage": "The @ button allows you to invite people by adding them to the group.",
    "chathere": "Chat here...",
    "enterkeyword": "Please enter some keywords.",
    "emailstring1": "You have been requested to be added in the group.<br> Please click the below link to be added.",
    "emailstring2": "Tapmate will be sending you a sentiment please",
    "userselected1": "you have selected",
    "pushTitle": "Did you know?",
    "push1": "Express! Tap high to like, tap right to share. When seeing the image big.",
    "push2": "Guess! Second tap guesses your buddy's reaction. They will be see it and respond instantly.",
    "push3": "Be seen! At a glance you’ll know what people think about styles, memes and more!",
    "push4": "Show face! Be known for your taste by tagging things on Instagram and expressing yourself in Tapmate.",
    "push5": "Opinonate! Long press the big pic to say what you love or hate about it. For example write something to the right if you really stand by it.",
    "type2": "You liked this on Instagram",
    "type3": "unfefine",
    "type4": "This has been shared loudly by someone or many someones.",
    "type8": "This is popular on Instagram.",
    "type81":"Don’t ask us why.", 
    "type9": "Search Result",
    "type31": "This image is shared on Facebook",
    "type32": "You liked this on Facebook",
    "type1": "Someone is dying to know what you’ll think about this.",
    "userselected2": "Next tap the big pic to guess senders position. What’s the face should be around here somewhere...",
     "JRTab1": "<h2>Feeds #1</h2><p>Nuff said. When things are shared they show up here. The more they’re ‘shared’ the higher they fly...</p>",
    "JRTab2": "<h2>The Big Picture #2</h2><p>To the right means that you share the sentiment. Share and let it fly! See what we did there? yes? </p>",
    "JRTab3": "<h2>Like #3</h2><p> Prefer to love? That’s all the way at the top. Show your love!</p>",
    "JRTab4": "<h2>Share #4</h2><p>Screaming from the rooftops more your style? That’s all the way to the right. This promotes and shows face. Make it fly up the feed!</p>",
    "JRTab5": "<h2>Current Follows #5</h2><p>It works with classes, and only on the first visible element with that class.</p>",
    "JRTab6": "<h2>Other faces in this space #6</h2><p>Other users. Ranked by last time they were seen. Try guessing their positions! They’ll probably get back to you.</p>",
    "JRTab7": "<h2>Your people on Facebook #7</h2><p>When a pic makes you think of one of them, call them out! Select them here and tap the The Big Picture to guess what they think. A personal touch to the message is a good way to get them to pay attention.</p>",
    "JRTab8": "<h2>Instagram people #8</h2><p>It’s recommended to use the instagram button to open the app and comment there. Also tag things with #r and other hashy types!</p>"
};
language.html = [
        ["a#aboutUsButton","about"],
        ["a#alreadyMessage","alreadyMessage"],
        ["a#loginButton","Login With Instagram"],
        ["a#logout","Logout"],
        // ["a#contest","Contest"],
        ["a#shareApp","shareApp"],
        ["a#pushNotification","Push Notification"],
        ["a#languageButton","languageButton"],
        ["b#Recentslabel","Recentslabel"],
        ["div#menuGame","Game"],
        ["div#accounts","accounts"],
        ["div#settings","settings"],
        ["div#tapmate","tapmate"],
        ["div#menuHelp","help"],
        ["div#menubug","menubug"],
        ["label#appOptimize","optimize"],
        ["a#contactUsButton","Contact Us"],
        ["a#tutorialButtonMenu","Tutorial"],
        ["a#instruction","Instruction"],
        ["a#startWalkthrough","Walkthrough"],
        ["a#ContactUsPopUp","ContactUsPopUp"],
        ["a#termsandcondition","termsandcondition"],
        ["a#AboutUsPopUp","AboutUsPopUp"],
        ["a#videotutorial","videotutorial"],
        ["a#loginwithInsta","loginwithInsta"],
        ["a#loginwithfb","loginwithfb"],
        ["a#loginwithgoog","loginwithgoog"],
        ["a#sendMail","sendMail"]
    ]